// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxjgzi6UfQ79_FCla9ODFcN1r--f-Isc',
    appId: '1:740977594770:web:973a0036ed38841d63b14b',
    messagingSenderId: '740977594770',
    projectId: 'app-custos-firebase',
    authDomain: 'app-custos-firebase.firebaseapp.com',
    storageBucket: 'app-custos-firebase.appspot.com',
    measurementId: 'G-F2RVTXWKMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHysProPdGgjjn4rfffS8_6VlfR4FNdNc',
    appId: '1:740977594770:android:eb64e46856fbfb9c63b14b',
    messagingSenderId: '740977594770',
    projectId: 'app-custos-firebase',
    storageBucket: 'app-custos-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4guvyHerr7wYHk1dWoty_x7HJal13vHU',
    appId: '1:740977594770:ios:365c3e2d3a2ce26863b14b',
    messagingSenderId: '740977594770',
    projectId: 'app-custos-firebase',
    storageBucket: 'app-custos-firebase.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4guvyHerr7wYHk1dWoty_x7HJal13vHU',
    appId: '1:740977594770:ios:ca46e10084123c9c63b14b',
    messagingSenderId: '740977594770',
    projectId: 'app-custos-firebase',
    storageBucket: 'app-custos-firebase.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
